import type { ConfirmedText4cBrief } from './text4cBrief';
import { legacySummaryToText4cBrief } from './text4cBrief';
import { buildText4cImagePrompt } from './text4cPromptBuilder';

export async function generateFloorplanImage4c(input: ConfirmedText4cBrief | string): Promise<string> {
  const brief = typeof input === 'string'
    ? legacySummaryToText4cBrief(input)
    : input;
  const prompt = buildText4cImagePrompt(brief);
  const promptWords = prompt.trim().split(/\s+/).length;

  console.log(`[Text 4.0 C] Generating image via proxy API (${brief.renderingProfileId}, ${promptWords} words)...`);
  const startTime = Date.now();

  try {
    const response = await fetch('/api/text2plan/image', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ prompt }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`API error (${response.status}): ${errorText}`);
    }

    const data = await response.json();
    const elapsed = Date.now() - startTime;
    const serverTiming = Number.isFinite(data.generationMs)
      ? `; Vertex proxy ${data.generationMs}ms (auth ${data.authMs ?? '?'}ms, model ${data.vertexMs ?? '?'}ms)`
      : '';
    console.log(`[Text 4.0 C] Image generation completed in ${elapsed}ms${serverTiming}`);

    if (!data.imageBytes) {
      throw new Error('No image was generated by the API.');
    }

    return `data:image/jpeg;base64,${data.imageBytes}`;
  } catch (error: any) {
    console.error('[Text 4.0 C] Image Generation Error:', error);
    throw new Error(`Failed to generate architectural image: ${error.message || error}`);
  }
}
