import type { ConfirmedText4hBrief } from './text4hBrief';
import { legacySummaryToText4hBrief } from './text4hBrief';
import { buildText4hImagePrompt } from './text4hPromptBuilder';
import { enforceText4hGeneratedImageAspect } from './text4hGeneratedImageAspectGuard';

export interface Text4hImageGenerationOptions {
  variantIndex?: number;
  variantCount?: number;
}

export async function generateFloorplanImage4h(
  input: ConfirmedText4hBrief | string,
  options: Text4hImageGenerationOptions = {},
): Promise<string> {
  const brief = typeof input === 'string'
    ? legacySummaryToText4hBrief(input)
    : input;
  const basePrompt = buildText4hImagePrompt(brief);
  const variantInstruction = options.variantIndex && options.variantCount
    ? `\n\nVARIANT REQUEST: Produce independent compliant alternative ${options.variantIndex} of ${options.variantCount}. Preserve every confirmed dimension, room, adjacency, boundary, circulation, privacy, and architectural constraint. Vary only aspects that the confirmed brief leaves unconstrained.`
    : '';
  const prompt = `${basePrompt}${variantInstruction}`;
  const promptWords = prompt.trim().split(/\s+/).length;

  console.log(`[Text 4.0 H] Generating image via proxy API (backend-selected Gemini model, ${brief.renderingProfileId}, ${promptWords} words)...`);
  const startTime = Date.now();

  try {
    const response = await fetch('/api/text4h/image', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ prompt }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`API error (${response.status}): ${errorText}`);
    }

    const data = await response.json();
    const elapsed = Date.now() - startTime;
    const serverTiming = Number.isFinite(data.generationMs)
      ? `; Vertex proxy ${data.generationMs}ms (auth ${data.authMs ?? '?'}ms, model ${data.vertexMs ?? '?'}ms)`
      : '';
    console.log(`[Text 4.0 H] Image generation completed in ${elapsed}ms${serverTiming}`);

    if (!data.imageBytes) {
      throw new Error('No image was generated by the API.');
    }

    const generatedDataUrl = `data:image/jpeg;base64,${data.imageBytes}`;
    const aspectResult = await enforceText4hGeneratedImageAspect(generatedDataUrl, brief);
    if (aspectResult.applied) {
      console.info(
        `[Text 4.0 H] Locked-frame aspect corrected locally from ${aspectResult.sourceRatio?.toFixed(4)} to ${aspectResult.correctedRatio?.toFixed(4)} (target ${aspectResult.targetRatio?.toFixed(4)}).`,
      );
    } else if (aspectResult.reason === 'frame-not-detected' || aspectResult.reason === 'unsafe-correction') {
      console.warn(`[Text 4.0 H] Locked-frame aspect guard did not alter the image: ${aspectResult.reason}.`);
    }
    return aspectResult.dataUrl;
  } catch (error: any) {
    console.error('[Text 4.0 H] Image Generation Error:', error);
    throw new Error(`Failed to generate architectural image: ${error.message || error}`);
  }
}
