import type { ConfirmedText4gBrief } from './text4gBrief';
import { legacySummaryToText4gBrief } from './text4gBrief';
import { buildText4gImagePrompt } from './text4gPromptBuilder';
import { enforceText4gGeneratedImageAspect } from './text4gGeneratedImageAspectGuard';

export async function generateFloorplanImage4g(input: ConfirmedText4gBrief | string): Promise<string> {
  const brief = typeof input === 'string'
    ? legacySummaryToText4gBrief(input)
    : input;
  const prompt = buildText4gImagePrompt(brief);
  const promptWords = prompt.trim().split(/\s+/).length;

  console.log(`[Text 4.0 G] Generating image via proxy API (${brief.renderingProfileId}, ${promptWords} words)...`);
  const startTime = Date.now();

  try {
    const response = await fetch('/api/text4g/image', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ prompt }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`API error (${response.status}): ${errorText}`);
    }

    const data = await response.json();
    const elapsed = Date.now() - startTime;
    const serverTiming = Number.isFinite(data.generationMs)
      ? `; Vertex proxy ${data.generationMs}ms (auth ${data.authMs ?? '?'}ms, model ${data.vertexMs ?? '?'}ms)`
      : '';
    console.log(`[Text 4.0 G] Image generation completed in ${elapsed}ms${serverTiming}`);

    if (!data.imageBytes) {
      throw new Error('No image was generated by the API.');
    }

    const generatedDataUrl = `data:image/jpeg;base64,${data.imageBytes}`;
    const aspectResult = await enforceText4gGeneratedImageAspect(generatedDataUrl, brief);
    if (aspectResult.applied) {
      console.info(
        `[Text 4.0 G] Locked-frame aspect corrected locally from ${aspectResult.sourceRatio?.toFixed(4)} to ${aspectResult.correctedRatio?.toFixed(4)} (target ${aspectResult.targetRatio?.toFixed(4)}).`,
      );
    } else if (aspectResult.reason === 'frame-not-detected' || aspectResult.reason === 'unsafe-correction') {
      console.warn(`[Text 4.0 G] Locked-frame aspect guard did not alter the image: ${aspectResult.reason}.`);
    }
    return aspectResult.dataUrl;
  } catch (error: any) {
    console.error('[Text 4.0 G] Image Generation Error:', error);
    throw new Error(`Failed to generate architectural image: ${error.message || error}`);
  }
}
