import type { ConfirmedText4jBrief } from './text4jBrief';
import { legacySummaryToText4jBrief } from './text4jBrief';
import { buildText4jImagePrompt } from './text4jPromptBuilder';
import { enforceText4jGeneratedImageAspect } from './text4jGeneratedImageAspectGuard';

export async function generateFloorplanImage4j(input: ConfirmedText4jBrief | string): Promise<string> {
  const brief = typeof input === 'string'
    ? legacySummaryToText4jBrief(input)
    : input;
  const prompt = buildText4jImagePrompt(brief);
  const promptWords = prompt.trim().split(/\s+/).length;

  const targetModel = brief.imageModel || 'gemini-3.1-flash-lite-image';
  console.log(`[Text 4.0 J] Generating image via proxy API (${targetModel}, ${brief.renderingProfileId}, ${promptWords} words)...`);
  const startTime = Date.now();

  try {
    const response = await fetch('/api/text4j/image', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ prompt, imageModel: targetModel }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`API error (${response.status}): ${errorText}`);
    }

    const data = await response.json();
    const elapsed = Date.now() - startTime;
    const serverTiming = Number.isFinite(data.generationMs)
      ? `; Vertex proxy ${data.generationMs}ms (auth ${data.authMs ?? '?'}ms, model ${data.vertexMs ?? '?'}ms)`
      : '';
    console.log(`[Text 4.0 J] Image generation completed in ${elapsed}ms${serverTiming}`);

    if (!data.imageBytes) {
      throw new Error('No image was generated by the API.');
    }

    const generatedDataUrl = `data:image/jpeg;base64,${data.imageBytes}`;
    const aspectResult = await enforceText4jGeneratedImageAspect(generatedDataUrl, brief);
    if (aspectResult.applied) {
      console.info(
        `[Text 4.0 J] Locked-frame aspect corrected locally from ${aspectResult.sourceRatio?.toFixed(4)} to ${aspectResult.correctedRatio?.toFixed(4)} (target ${aspectResult.targetRatio?.toFixed(4)}).`,
      );
    } else if (aspectResult.reason === 'frame-not-detected' || aspectResult.reason === 'unsafe-correction') {
      console.warn(`[Text 4.0 J] Locked-frame aspect guard did not alter the image: ${aspectResult.reason}.`);
    }
    return aspectResult.dataUrl;
  } catch (error: any) {
    console.error('[Text 4.0 J] Image Generation Error:', error);
    throw new Error(`Failed to generate architectural image: ${error.message || error}`);
  }
}
