import { GoogleGenAI } from '@google/genai';

// Initialize the Google Gen AI SDK
const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

export async function generateFloorplanImage4b(designSummary: string): Promise<string> {
  const isImperial = /sq\s*ft|sqft|ft|feet|inch|'|imperial/i.test(designSummary);
  const unitFormat = isImperial 
    ? "imperial units (feet and inches, e.g., '12\\'-0\" x 10\\'-0\"')"
    : "metric units (meters, e.g., '3.6m x 3.0m')";

  const BASE_IMAGEN_PROMPT = `A professional 2D architectural floor plan rendered on a clean, solid white background. High-contrast minimalist style. All structural exterior walls are exactly 9 inches thick and filled with a solid, pure black color. All interior partition walls are exactly 4.5 inches thick and also filled with solid black. No wall shading, no textures, and no patterns. Doors are drawn as clean single-line arcs showing swing direction. Windows are represented by simple parallel lines within the black walls. Crisp, highly legible sans-serif black text labels each room with its name and exact dimensions underneath (e.g., 'Room Name\\n00\\'-0" x 00\\'-0"'). No furniture layout, no flooring textures, and no color fills outside of the black walls. The layout must perfectly adhere to the following specific architectural requirements:`;

  const prompt = `${BASE_IMAGEN_PROMPT}\n\n${designSummary}`;

  console.log('[Text 4.0 B] Generating image via proxy API...');
  const startTime = Date.now();

  try {
    const response = await fetch('/api/text2plan/image', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ prompt })
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`API error (${response.status}): ${errorText}`);
    }

    const data = await response.json();
    
    const elapsed = Date.now() - startTime;
    console.log(`[Text 4.0 B] Image generation completed in ${elapsed}ms`);

    if (!data.imageBytes) {
      throw new Error("No image was generated by the API.");
    }

    return `data:image/jpeg;base64,${data.imageBytes}`;
  } catch (error: any) {
    console.error('[Text 4.0 B] Image Generation Error:', error);
    throw new Error(`Failed to generate architectural image: ${error.message || error}`);
  }
}
