export interface Workflow {
  id: number;
  slug: string;
  name: string;
  description: string;
  hubCategory: 'image_studio' | 'raster_canvas' | 'video_studio' | 'gen_3d';
  input_types: string[];
  output_types: string[];
  provider: 'vertex_image' | 'gemini_analysis' | 'controlnet_gpu' | 'veo_video' | 'trellis_3d' | 'local_adjustment';
  default_model: string;
  allowed_models: string[];
  model_dropdown: boolean;
  prompt_template: string;
  preservation_policy?: string;
  required_fields: string[];
  optional_fields: string[];
  default_values: Record<string, any>;
  estimated_time: string;
  async: boolean;
  manual_test_criteria: string;
  prompt_version: string;
}

const RAW_WORKFLOWS: Record<number, Omit<Workflow, 'hubCategory'>> = {
  1: {
    id: 1,
    slug: 'text-to-render',
    name: 'Text to Render',
    description: 'Create photorealistic renders from text prompts or reference images.',
    input_types: ['text', 'image/png', 'image/jpeg', 'image/webp', 'image/heic', 'image/heif'],
    output_types: ['image/png'],
    provider: 'vertex_image',
    default_model: 'gemini-3-pro-image',
    allowed_models: ['gemini-3-pro-image', 'gemini-3.1-flash-image', 'gemini-3.1-flash-lite-image'],
    model_dropdown: true,
    prompt_template: 'TASK: Create a photorealistic architectural visualization.\nPROJECT: {{project_type}}\nSCENE: {{space_type}}\nDESIGN DIRECTION: {{architectural_style}} {{interior_style}}\nDESIGN DESCRIPTION: {{design_intent}}\nMATERIAL PALETTE: {{materials}}\nCOLOR PALETTE: {{colors}}\nFURNITURE: {{furniture}}\nLIGHTING: {{lighting}}\nTIME OF DAY: {{time_of_day}}\nCAMERA: {{camera_angle}} {{lens}} {{composition}}\nENVIRONMENT: {{location_context}} {{landscape}}\nPEOPLE: {{people}}\nMOOD: {{mood}}\nUSER REQUIREMENTS: {{custom_instruction}}\n{{UNIVERSAL_QUALITY_BLOCK}}\nDo not create warped architecture, distorted furniture, floating objects, random text, logos or watermarks.',
    required_fields: ['user_input'],
    optional_fields: ['style', 'materials', 'colors', 'camera_angle', 'lighting', 'mood', 'people', 'landscape', 'custom_instruction'],
    default_values: {},
    estimated_time: '10-35 sec (Pro) / 4-12 sec (Flash)',
    async: false,
    manual_test_criteria: 'Pass when: Prompt adherence >= 4/5, Photorealism >= 4/5, Architectural plausibility >= 4/5, Material realism >= 4/5, Composition/camera quality >= 4/5, No major AI artifacts.',
    prompt_version: 'text_to_render:v1'
  },
  2: {
    id: 2,
    slug: 'sketch-to-render',
    name: 'Sketch to Render',
    description: 'Convert architectural sketches into photorealistic renders.',
    input_types: ['image/png', 'image/jpeg', 'image/webp', 'image/heic', 'image/heif'],
    output_types: ['image/png'],
    provider: 'controlnet_gpu',
    default_model: 'flux-2-pro',
    allowed_models: ['flux-2-pro', 'stable-diffusion-xl'],
    model_dropdown: true,
    prompt_template: 'TASK: Convert the supplied architectural sketch into a photorealistic architectural visualization.\nSTRUCTURAL PRIORITY: Treat sketch lines as authoritative design geometry. Preserve: building massing, roof form, major edges, façade divisions, openings, doors, windows, floor levels, primary perspective.\nDESIGN STYLE: {{style}}\nMATERIALS: {{materials}}\nDESIGN DETAILS: {{design_intent}}\nENVIRONMENT: {{environment}}\nLANDSCAPE: {{landscape}}\nLIGHTING: {{lighting}}\nMaintain the perspective implied by the source sketch.\nUSER REQUIREMENTS: {{custom_instruction}}\n{{UNIVERSAL_QUALITY_BLOCK}}',
    required_fields: ['source_image'],
    optional_fields: ['style', 'materials', 'lighting', 'environment', 'landscape', 'custom_instruction'],
    default_values: { controlnet_type: 'scribble', controlnet_conditioning_scale: 0.8 },
    estimated_time: '15-45 sec (Warm) / 45-120 sec (Cold)',
    async: true,
    manual_test_criteria: 'Sketch geometry preservation >= 4/5, Window/door correspondence >= 90% visually, Perspective preservation >= 4/5, Photorealism >= 4/5, Material adherence >= 4/5, No major added/removed structural elements.',
    prompt_version: 'sketch_to_render:v1'
  },
  3: {
    id: 3,
    slug: 'elevation-to-render',
    name: 'Elevation to Render',
    description: 'Convert architectural elevations into realistic façade renders.',
    input_types: ['image/png', 'image/jpeg', 'image/webp', 'image/heic', 'image/heif'],
    output_types: ['image/png'],
    provider: 'controlnet_gpu',
    default_model: 'stable-diffusion-xl',
    allowed_models: ['stable-diffusion-xl'],
    model_dropdown: false,
    prompt_template: 'TASK: Convert the supplied architectural elevation into a realistic architectural façade visualization.\nELEVATION AUTHORITY: Preserve façade proportions, floor heights, roofline, windows, doors, balconies and structural grid. Do not reposition architectural openings.\nMATERIALS: {{materials}}\nSTYLE: {{architectural_style}}\nGLAZING: {{glazing}}\nLANDSCAPE: {{landscape}}\nLIGHTING: {{lighting}}\nENVIRONMENT: {{environment}}\nUSER REQUIREMENTS: {{custom_instruction}}\nCreate realistic façade depth, material joints, glazing reflections and recess shadows while maintaining source geometry.',
    required_fields: ['source_image'],
    optional_fields: ['materials', 'architectural_style', 'glazing', 'landscape', 'lighting', 'environment', 'custom_instruction'],
    default_values: { controlnet_type: 'lineart', controlnet_conditioning_scale: 0.9 },
    estimated_time: '20-60 sec (Warm) / 60-120 sec (Cold)',
    async: true,
    manual_test_criteria: 'Opening location match >= 95%, Floor-height/massing match >= 4/5, Façade material quality >= 4/5, No unrequested geometry change, Overall photorealism >= 4/5.',
    prompt_version: 'elevation_to_render:v1'
  },
  4: {
    id: 4,
    slug: 'three-d-model-to-render',
    name: '3D Model to Render',
    description: 'Convert 3D model views into photorealistic renders.',
    input_types: ['image/png'], // expects depth pass image
    output_types: ['image/png'],
    provider: 'controlnet_gpu',
    default_model: 'stable-diffusion-xl',
    allowed_models: ['stable-diffusion-xl'],
    model_dropdown: false,
    prompt_template: 'TASK: Transform the supplied depth/geometry reference into a photorealistic architectural rendering.\nGEOMETRY AUTHORITY: Preserve scene geometry, massing, camera, floor levels and primary openings.\nSTYLE: {{style}}\nMATERIALS: {{materials}}\nFURNITURE: {{furniture}}\nLANDSCAPE: {{landscape}}\nLIGHTING: {{lighting}}\nATMOSPHERE: {{mood}}\nUSER REQUIREMENTS: {{custom_instruction}}\nApply physically believable materials and lighting while respecting supplied geometry.',
    required_fields: ['source_image'], // depth pass input
    optional_fields: ['style', 'materials', 'furniture', 'landscape', 'lighting', 'mood', 'custom_instruction'],
    default_values: { controlnet_type: 'depth', controlnet_conditioning_scale: 0.75 },
    estimated_time: '20-60 sec (Warm) / 60-120 sec (Cold)',
    async: true,
    manual_test_criteria: '3D silhouette preservation >= 95%, Camera match >= 4/5, Depth/occlusion correctness >= 4/5, Materials >= 4/5, Photorealism >= 4/5, No major geometry hallucination.',
    prompt_version: '3d_model_to_render:v1'
  },
  5: {
    id: 5,
    slug: 'image-to-render',
    name: 'Image to Render',
    description: 'Transform an existing image into a photorealistic architectural render.',
    input_types: ['image/png', 'image/jpeg', 'image/webp', 'image/heic', 'image/heif'],
    output_types: ['image/png'],
    provider: 'vertex_image',
    default_model: 'gemini-3.1-flash-image',
    allowed_models: ['gemini-3-pro-image', 'gemini-3.1-flash-image', 'gemini-3.1-flash-lite-image'],
    model_dropdown: true,
    prompt_template: 'TASK: Transform the supplied image into a professional photorealistic architectural visualization.\n{{SOURCE_IMAGE_AUTHORITY}}\nImprove: materials, lighting, textures, reflections, shadows, atmospheric depth, photographic finish.\nTARGET STYLE: {{style}}\nMATERIAL CHANGES: {{materials}}\nLIGHTING: {{lighting}}\nREQUESTED CHANGES: {{requested_changes}}\nUSER REQUIREMENTS: {{custom_instruction}}\n{{UNIVERSAL_QUALITY_BLOCK}}',
    required_fields: ['source_image'],
    optional_fields: ['style', 'materials', 'lighting', 'requested_changes', 'custom_instruction'],
    default_values: {},
    estimated_time: '6-18 sec (Recommended)',
    async: false,
    manual_test_criteria: 'Original geometry preservation >= 4/5, Camera preservation >= 4/5, Visual-quality improvement clearly noticeable, Prompt adherence >= 4/5, No unrelated redesign, Photorealism >= 4/5.',
    prompt_version: 'image_to_render:v1'
  },
  6: {
    id: 6,
    slug: 'floor-plan-to-render',
    name: 'Floor Plan to Render',
    description: 'Convert a floor plan into a rendered/furnished visualization.',
    input_types: ['image/png', 'image/jpeg', 'image/webp', 'image/heic', 'image/heif'],
    output_types: ['image/png'],
    provider: 'controlnet_gpu',
    default_model: 'flux-2-pro',
    allowed_models: ['flux-2-pro', 'stable-diffusion-xl'],
    model_dropdown: false,
    prompt_template: 'TASK: Convert the supplied architectural floor plan into a furnished top-down architectural visualization.\nPLAN AUTHORITY: Preserve external walls, internal partitions, doors, windows, room boundaries, circulation and relative room proportions.\nROOM FUNCTIONS: {{room_labels}}\nSTYLE: {{style}}\nFLOOR MATERIALS: {{floor_materials}}\nFURNITURE: {{furniture}}\nCOLORS: {{colors}}\nUSER REQUIREMENTS: {{custom_instruction}}\nProduce a clean orthographic top-down visualization.',
    required_fields: ['source_image'],
    optional_fields: ['room_labels', 'style', 'floor_materials', 'furniture', 'colors', 'custom_instruction'],
    default_values: { controlnet_type: 'segment', controlnet_conditioning_scale: 0.8 },
    estimated_time: '30-90 sec (Warm) / 60-150 sec (Cold)',
    async: true,
    manual_test_criteria: 'Wall layout match >= 95%, Door/window consistency >= 90%, Room-function correctness >= 90%, Furniture scale/circulation >= 4/5, No major plan alteration, Rendering quality >= 4/5.',
    prompt_version: 'floorplan_to_render:v1'
  },
  7: {
    id: 7,
    slug: 'render-to-moodboard',
    name: 'Render to Moodboard',
    description: 'Extract the design language of a render and create a moodboard.',
    input_types: ['image/png', 'image/jpeg', 'image/webp', 'image/heic', 'image/heif'],
    output_types: ['image/png'], // returns the composed moodboard / swatches
    provider: 'gemini_analysis', // uses Stage 1: gemini-2.5-flash -> Stage 2: gemini-3.1-flash-image
    default_model: 'gemini-2.5-flash',
    allowed_models: ['gemini-2.5-flash'],
    model_dropdown: false,
    prompt_template: 'Analyze the supplied architectural render. Return structured JSON containing: design style, primary color hex codes, woods, stones, metals, fabrics, flooring, wall finishes, furniture style, lighting style, decorative elements, design keywords.',
    required_fields: ['source_image'],
    optional_fields: [],
    default_values: {},
    estimated_time: '30-90 sec (requires swatch generation)',
    async: true,
    manual_test_criteria: 'Extracted palette resemblance >= 4/5, Material identification accuracy >= 4/5, Swatches visually correspond to source >= 4/5, Moodboard design coherence >= 4/5, No unrelated style invention.',
    prompt_version: 'render_to_moodboard:v1'
  },
  8: {
    id: 8,
    slug: 'render-variation',
    name: 'Render Variation',
    description: 'Generate alternative design variations of an existing render.',
    input_types: ['image/png', 'image/jpeg', 'image/webp', 'image/heic', 'image/heif'],
    output_types: ['image/png'],
    provider: 'vertex_image',
    default_model: 'gemini-3.1-flash-image',
    allowed_models: ['gemini-3-pro-image', 'gemini-3.1-flash-image', 'gemini-3.1-flash-lite-image'],
    model_dropdown: true,
    prompt_template: 'TASK: Create a design variation of the supplied architectural render.\nSTRUCTURAL LOCK: Preserve camera, perspective, architecture, openings and spatial layout.\nCHANGE ONLY: {{variation_scope}}\nTARGET STYLE: {{style}}\nMATERIALS: {{materials}}\nCOLORS: {{colors}}\nFURNITURE: {{furniture}}\nUSER REQUIREMENTS: {{custom_instruction}}\nTHE OUTPUT MUST REMAIN RECOGNIZABLY THE SAME PROJECT FROM THE SAME VIEWPOINT.',
    required_fields: ['source_image'],
    optional_fields: ['variation_scope', 'style', 'materials', 'colors', 'furniture', 'custom_instruction'],
    default_values: {},
    estimated_time: '6-18 sec',
    async: false,
    manual_test_criteria: 'Same-project recognition >= 4/5, Camera preservation >= 4/5, Requested variation clearly visible, Unrequested changes minimal, Overall quality >= 4/5.',
    prompt_version: 'render_variation:v1'
  },
  9: {
    id: 9,
    slug: 'edit-canvas',
    name: 'Edit Canvas',
    description: 'Select areas and make localized AI edits.',
    input_types: ['image/png', 'image/jpeg', 'image/webp', 'image/heic', 'image/heif'],
    output_types: ['image/png'],
    provider: 'vertex_image',
    default_model: 'gemini-3-pro-image',
    allowed_models: ['gemini-3-pro-image', 'gemini-3.1-flash-image', 'gemini-3.1-flash-lite-image'],
    model_dropdown: true,
    prompt_template: 'TASK: Edit only the selected target region.\nREQUESTED EDIT: {{edit_instruction}}\nRestrict modification to the selected target. Preserve everything unrelated to the request. Match the existing scale, perspective, lighting, shadows, reflections and photographic character. Do not redesign surrounding areas.',
    required_fields: ['source_image', 'mask'],
    optional_fields: ['edit_instruction'],
    default_values: {},
    estimated_time: '10-35 sec',
    async: false,
    manual_test_criteria: 'Edit contained inside intended area >= 4/5, Boundary blending >= 4/5, Requested edit accuracy >= 4/5, Protected-area preservation >= 95%, No visible seams/ghosting.',
    prompt_version: 'edit_canvas:v1'
  },
  10: {
    id: 10,
    slug: 'conversational-edit',
    name: 'Conversational Edit',
    description: 'Edit an image through natural-language conversation.',
    input_types: ['image/png', 'image/jpeg', 'image/webp', 'image/heic', 'image/heif'],
    output_types: ['image/png'],
    provider: 'vertex_image',
    default_model: 'gemini-3-pro-image',
    allowed_models: ['gemini-3-pro-image', 'gemini-3.1-flash-image', 'gemini-3.1-flash-lite-image'],
    model_dropdown: true,
    prompt_template: 'You are an architectural image-editing engine. Each instruction modifies the current image state. For localized requests: modify only relevant objects, preserve architecture, preserve camera, preserve unrelated elements, maintain realistic scale and lighting, preserve previous accepted edits unless explicitly reversed.',
    required_fields: ['source_image', 'user_input'],
    optional_fields: ['conversation_history'],
    default_values: {},
    estimated_time: '15-45 sec',
    async: false,
    manual_test_criteria: 'Target-object identification >= 90%, Turn-to-turn edit memory >= 4/5, Previous accepted edits preserved, Locality of changes >= 4/5, Final realism >= 4/5.',
    prompt_version: 'conversational_edit:v1'
  },
  11: {
    id: 11,
    slug: 'select-and-modify',
    name: 'Select and Modify',
    description: 'Select a specific object/surface and modify it.',
    input_types: ['image/png', 'image/jpeg', 'image/webp', 'image/heic', 'image/heif'],
    output_types: ['image/png'],
    provider: 'vertex_image',
    default_model: 'gemini-3-pro-image',
    allowed_models: ['gemini-3-pro-image', 'gemini-3.1-flash-image', 'gemini-3.1-flash-lite-image'],
    model_dropdown: true,
    prompt_template: 'TARGET: {{identified_object}}\nREQUESTED MODIFICATION: {{modification}}\nModify only the selected object. Preserve its position and physically appropriate scale unless requested otherwise. Match perspective, lighting, shadows and reflections. Everything outside the target should remain unchanged.',
    required_fields: ['source_image', 'mask'],
    optional_fields: ['identified_object', 'modification'],
    default_values: {},
    estimated_time: '10-35 sec',
    async: false,
    manual_test_criteria: 'Correct selected object >= 95%, Edit spill outside target minimal, Requested change >= 4/5, Lighting integration >= 4/5, Scene preservation >= 4/5.',
    prompt_version: 'select_and_modify:v1'
  },
  12: {
    id: 12,
    slug: 'annotate-image',
    name: 'Annotate Image',
    description: 'Add structured architectural/design annotations.',
    input_types: ['image/png', 'image/jpeg', 'image/webp', 'image/heic', 'image/heif'],
    output_types: ['text/json'],
    provider: 'gemini_analysis',
    default_model: 'gemini-2.5-flash',
    allowed_models: ['gemini-2.5-flash'],
    model_dropdown: false,
    prompt_template: 'Identify significant architectural/interior-design elements. For each object return: id category label description bounding box confidence. Use normalized bounding boxes: [ymin, xmin, ymax, xmax]. Return valid JSON only.',
    required_fields: ['source_image'],
    optional_fields: [],
    default_values: {},
    estimated_time: '2-8 sec',
    async: false,
    manual_test_criteria: 'Object identification precision >= 90%, Bounding-box placement visually correct >= 90%, Labels meaningful >= 4/5, No hallucinated major objects, Frontend annotations align with image.',
    prompt_version: 'annotate_image:v1'
  },
  13: {
    id: 13,
    slug: 'remove-object',
    name: 'Remove Object',
    description: 'Remove a selected object and reconstruct its background.',
    input_types: ['image/png', 'image/jpeg', 'image/webp', 'image/heic', 'image/heif'],
    output_types: ['image/png'],
    provider: 'vertex_image',
    default_model: 'gemini-3-pro-image',
    allowed_models: ['gemini-3-pro-image', 'gemini-3.1-flash-image', 'gemini-3.1-flash-lite-image'],
    model_dropdown: true,
    prompt_template: 'Remove only: {{target_object}}\nReconstruct the hidden background in a physically plausible way. Continue surrounding wall, floor, ceiling, materials, architecture, lighting and reflections. The result should appear as if the object never existed. Do not add a replacement object. Do not modify unrelated scene elements.',
    required_fields: ['source_image', 'mask'],
    optional_fields: ['target_object'],
    default_values: {},
    estimated_time: '10-35 sec',
    async: false,
    manual_test_criteria: 'Object fully removed, No ghosting, Background reconstruction >= 4/5, Material continuation >= 4/5, Protected scene unchanged >= 4/5.',
    prompt_version: 'remove_object:v1'
  },
  14: {
    id: 14,
    slug: 'extend-image',
    name: 'Extend Image',
    description: 'Expand a render beyond its existing boundaries.',
    input_types: ['image/png', 'image/jpeg', 'image/webp', 'image/heic', 'image/heif'],
    output_types: ['image/png'],
    provider: 'vertex_image',
    default_model: 'gemini-3-pro-image',
    allowed_models: ['gemini-3-pro-image', 'gemini-3.1-flash-image', 'gemini-3.1-flash-lite-image'],
    model_dropdown: true,
    prompt_template: 'Extend the supplied image to {{target_aspect_ratio}}. Keep original image content unchanged. Generate only the additional surroundings required outside the original boundaries. Continue architecture, flooring, ceiling, landscape, sky, perspective, material patterns, lighting and shadows naturally. USER REQUIREMENTS: {{custom_instruction}}',
    required_fields: ['source_image'],
    optional_fields: ['target_aspect_ratio', 'custom_instruction'],
    default_values: {},
    estimated_time: '12-50 sec',
    async: false,
    manual_test_criteria: 'Original pixels/composition visually preserved, Extension seam invisible, Perspective continuation >= 4/5, Architectural plausibility >= 4/5, Lighting continuity >= 4/5.',
    prompt_version: 'extend_image:v1'
  },
  15: {
    id: 15,
    slug: 'virtual-staging',
    name: 'Virtual Staging',
    description: 'Furnish and decorate an empty room.',
    input_types: ['image/png', 'image/jpeg', 'image/webp', 'image/heic', 'image/heif'],
    output_types: ['image/png'],
    provider: 'vertex_image',
    default_model: 'gemini-3.1-flash-image',
    allowed_models: ['gemini-3-pro-image', 'gemini-3.1-flash-image', 'gemini-3.1-flash-lite-image'],
    model_dropdown: true,
    prompt_template: 'TASK: Virtually stage the supplied empty room.\nROOM AUTHORITY: Do not alter room dimensions, walls, windows, doors, ceiling, permanent architecture or camera.\nROOM TYPE: {{room_type}}\nSTYLE: {{style}}\nFURNITURE: {{furniture}}\nMATERIALS: {{materials}}\nCOLORS: {{colors}}\nMOOD: {{mood}}\nUse realistic furniture scale and circulation. Do not obstruct doors. Furniture must contact the floor naturally and cast plausible shadows.\n{{UNIVERSAL_QUALITY_BLOCK}}',
    required_fields: ['source_image'],
    optional_fields: ['room_type', 'style', 'furniture', 'materials', 'colors', 'mood'],
    default_values: {},
    estimated_time: '8-25 sec',
    async: false,
    manual_test_criteria: 'Room architecture preservation >= 95%, Furniture scale >= 4/5, Interior-design quality >= 4/5, Circulation plausibility >= 4/5, Lighting/shadow integration >= 4/5.',
    prompt_version: 'virtual_staging:v1'
  },
  16: {
    id: 16,
    slug: 'image-adjustments',
    name: 'Image Adjustments',
    description: 'Adjust brightness, contrast, saturation and related image properties.',
    input_types: ['image/png', 'image/jpeg', 'image/webp', 'image/heic', 'image/heif'],
    output_types: ['image/png'],
    provider: 'local_adjustment',
    default_model: 'pillow-opencv',
    allowed_models: ['pillow-opencv'],
    model_dropdown: false,
    prompt_template: '',
    required_fields: ['source_image'],
    optional_fields: ['brightness', 'contrast', 'saturation', 'temperature', 'tint', 'exposure', 'highlights', 'shadows', 'sharpness', 'gamma'],
    default_values: { brightness: 0, contrast: 0, saturation: 0, temperature: 0, tint: 0, exposure: 0, highlights: 0, shadows: 0, sharpness: 0, gamma: 1.0 },
    estimated_time: '< 1 sec',
    async: false,
    manual_test_criteria: 'Slider response deterministic, No geometry/content changes, Reset returns original image.',
    prompt_version: 'image_adjustments:v1'
  },
  17: {
    id: 17,
    slug: 'fix-people',
    name: 'Fix People',
    description: 'Correct distorted or unnatural people.',
    input_types: ['image/png', 'image/jpeg', 'image/webp', 'image/heic', 'image/heif'],
    output_types: ['image/png'],
    provider: 'vertex_image',
    default_model: 'gemini-3-pro-image',
    allowed_models: ['gemini-3-pro-image', 'gemini-3.1-flash-image', 'gemini-3.1-flash-lite-image'],
    model_dropdown: true,
    prompt_template: 'Correct the selected person\'s visible anatomical/generation problems. Correct: hands, fingers, limbs, face, body proportions, posture, clothing geometry, floor/furniture contact. Preserve approximate position, pose, scale, activity and surrounding architecture. Match lighting, shadows, depth of field and color temperature. Do not alter unrelated people or architecture.',
    required_fields: ['source_image', 'mask'],
    optional_fields: [],
    default_values: {},
    estimated_time: '10-35 sec',
    async: false,
    manual_test_criteria: 'Anatomy >= 4/5, Hands/face improved, Original position preserved, Architecture unchanged, Lighting integration >= 4/5.',
    prompt_version: 'fix_people:v1'
  },
  18: {
    id: 18,
    slug: 'populate-render',
    name: 'Populate Render',
    description: 'Add realistic people to architectural scenes.',
    input_types: ['image/png', 'image/jpeg', 'image/webp', 'image/heic', 'image/heif'],
    output_types: ['image/png'],
    provider: 'vertex_image',
    default_model: 'gemini-3.1-flash-image',
    allowed_models: ['gemini-3-pro-image', 'gemini-3.1-flash-image', 'gemini-3.1-flash-lite-image'],
    model_dropdown: true,
    prompt_template: 'Add realistic people to the supplied architectural visualization. NUMBER: {{people_count}}\nDESCRIPTION: {{people_description}}\nACTIVITY: {{activity}}\nPLACEMENT: {{placement}}\nPeople must have believable physical scale, respect perspective, contact actual surfaces, match lighting and cast plausible shadows. Do not alter architecture, furniture or camera.',
    required_fields: ['source_image'],
    optional_fields: ['people_count', 'people_description', 'activity', 'placement'],
    default_values: { people_count: 2 },
    estimated_time: '8-25 sec',
    async: false,
    manual_test_criteria: 'Human realism >= 4/5, Scale/perspective >= 4/5, Lighting integration >= 4/5, Architecture unchanged, No duplicate/distorted people.',
    prompt_version: 'populate_render:v1'
  },
  19: {
    id: 19,
    slug: 'change-camera-angle',
    name: 'Change Camera Angle',
    description: 'Create an approximate alternate viewpoint.',
    input_types: ['image/png', 'image/jpeg', 'image/webp', 'image/heic', 'image/heif'],
    output_types: ['video/mp4'],
    provider: 'veo_video',
    default_model: 'veo-3.1-lite',
    allowed_models: ['veo-3.1-lite'],
    model_dropdown: false,
    prompt_template: 'A smooth architectural camera movement approximately {{angle_change}} to the {{direction}}. Maintain the same architecture, materials, furniture and lighting. Use stable professional architectural cinematography. No moving walls. No shifting windows. No moving furniture. No geometry morphing. End on a clean, stable architectural composition suitable for extraction as a still frame.',
    required_fields: ['source_image', 'angle_change', 'direction'],
    optional_fields: [],
    default_values: { audio: false, duration_seconds: 4 },
    estimated_time: '1-5 min',
    async: true,
    manual_test_criteria: 'New viewpoint visibly changed, Project identity >= 4/5, Major geometry consistency >= 4/5, No visible object morphing, Final extracted frame sharp/stable.',
    prompt_version: 'change_camera_angle:v1'
  },
  20: {
    id: 20,
    slug: 'style-transfer',
    name: 'Style Transfer',
    description: 'Transfer the visual style of one image to another.',
    input_types: ['image/png', 'image/jpeg', 'image/webp', 'image/heic', 'image/heif'],
    output_types: ['image/png'],
    provider: 'vertex_image',
    default_model: 'gemini-3-pro-image',
    allowed_models: ['gemini-3-pro-image', 'gemini-3.1-flash-image', 'gemini-3.1-flash-lite-image'],
    model_dropdown: true,
    prompt_template: 'IMAGE 1 defines architecture, geometry, layout and camera. IMAGE 2 defines aesthetic style. Transfer from Image 2: materials, colors, furniture aesthetic, decorative language, lighting mood, visual atmosphere. Preserve from Image 1: architecture, geometry, spatial layout, perspective, structural openings. Do not copy unrelated geometry from Image 2.',
    required_fields: ['source_image', 'style_reference_image'],
    optional_fields: [],
    default_values: {},
    estimated_time: '10-35 sec',
    async: false,
    manual_test_criteria: 'Style resemblance >= 4/5, Base architecture preservation >= 4/5, No reference-geometry leakage, Material/color transfer >= 4/5, Photorealism >= 4/5.',
    prompt_version: 'style_transfer:v1'
  },
  21: {
    id: 21,
    slug: 'change-material',
    name: 'Change Material',
    description: 'Change the material of a selected surface.',
    input_types: ['image/png', 'image/jpeg', 'image/webp', 'image/heic', 'image/heif'],
    output_types: ['image/png'],
    provider: 'vertex_image',
    default_model: 'gemini-3-pro-image',
    allowed_models: ['gemini-3-pro-image', 'gemini-3.1-flash-image', 'gemini-3.1-flash-lite-image'],
    model_dropdown: true,
    prompt_template: 'Change only the material of: {{target_surface}}\nNEW MATERIAL: {{new_material}}\nColor: {{color}}\nTexture: {{texture}}\nFinish: {{finish}}\nRoughness: {{roughness}}\nPattern/veining: {{pattern}}\nJoints/grout: {{joints}}\nUse physically appropriate texture scale. Preserve exact surface geometry and all unrelated elements.',
    required_fields: ['source_image', 'mask', 'target_surface', 'new_material'],
    optional_fields: ['color', 'texture', 'finish', 'roughness', 'pattern', 'joints'],
    default_values: {},
    estimated_time: '10-35 sec',
    async: false,
    manual_test_criteria: 'Only selected surface changes, Material identity >= 4/5, Texture scale >= 4/5, Lighting/reflection response >= 4/5, Geometry unchanged.',
    prompt_version: 'change_material:v1'
  },
  22: {
    id: 22,
    slug: 'change-season',
    name: 'Change Season',
    description: 'Transform the environmental season.',
    input_types: ['image/png', 'image/jpeg', 'image/webp', 'image/heic', 'image/heif'],
    output_types: ['image/png'],
    provider: 'vertex_image',
    default_model: 'gemini-3.1-flash-image',
    allowed_models: ['gemini-3-pro-image', 'gemini-3.1-flash-image', 'gemini-3.1-flash-lite-image'],
    model_dropdown: true,
    prompt_template: 'Transform the supplied exterior visualization into {{target_season}}. Preserve building geometry, camera, permanent materials and hardscape. Update vegetation, ground condition, atmospheric color, sky and environmental lighting appropriately. Seasonal effects must be physically plausible. Do not redesign architecture.',
    required_fields: ['source_image', 'target_season'],
    optional_fields: ['mood'],
    default_values: {},
    estimated_time: '6-20 sec',
    async: false,
    manual_test_criteria: 'Season clearly recognizable, Architecture preservation >= 95%, Vegetation consistency >= 4/5, Weather/ground consistency >= 4/5, No unrealistic seasonal artifacts.',
    prompt_version: 'change_season:v1'
  },
  23: {
    id: 23,
    slug: 'change-time-of-day',
    name: 'Change Time of Day',
    description: 'Change the scene\'s lighting/time.',
    input_types: ['image/png', 'image/jpeg', 'image/webp', 'image/heic', 'image/heif'],
    output_types: ['image/png'],
    provider: 'vertex_image',
    default_model: 'gemini-3.1-flash-image',
    allowed_models: ['gemini-3-pro-image', 'gemini-3.1-flash-image', 'gemini-3.1-flash-lite-image'],
    model_dropdown: true,
    prompt_template: 'Change scene illumination to {{target_time_of_day}}. Preserve architecture, geometry, materials, landscape, objects and camera.\nLIGHTING: {{lighting_description}}\nSUN: {{sun_direction}}\nINTERIOR LIGHTING: {{interior_lighting}}\nUpdate shadows, glazing reflections and color temperature consistently. Do not modify the design itself.',
    required_fields: ['source_image', 'target_time_of_day'],
    optional_fields: ['lighting_description', 'sun_direction', 'interior_lighting'],
    default_values: {},
    estimated_time: '6-20 sec',
    async: false,
    manual_test_criteria: 'Target time visually convincing >= 4/5, Shadow direction consistency >= 4/5, Architecture unchanged, Window/reflection behavior >= 4/5, No excessive color grading.',
    prompt_version: 'change_time_of_day:v1'
  },
  24: {
    id: 24,
    slug: 'change-weather',
    name: 'Change Weather',
    description: 'Change weather and atmospheric conditions.',
    input_types: ['image/png', 'image/jpeg', 'image/webp', 'image/heic', 'image/heif'],
    output_types: ['image/png'],
    provider: 'vertex_image',
    default_model: 'gemini-3.1-flash-image',
    allowed_models: ['gemini-3-pro-image', 'gemini-3.1-flash-image', 'gemini-3.1-flash-lite-image'],
    model_dropdown: true,
    prompt_template: 'Change only environmental weather conditions to {{target_weather}}. Preserve architecture, geometry, materials, camera, landscape design and objects.\nWEATHER: {{weather_description}}\nATMOSPHERE: {{atmosphere}}\nGROUND: {{ground_condition}}\nSKY: {{sky}}\nLIGHT: {{lighting}}\nApply physically plausible wetness, reflection, fog, snow or diffused light as appropriate. Do not redesign architecture.',
    required_fields: ['source_image', 'target_weather'],
    optional_fields: ['weather_description', 'atmosphere', 'ground_condition', 'sky', 'lighting'],
    default_values: {},
    estimated_time: '6-20 sec',
    async: false,
    manual_test_criteria: 'Weather clearly recognizable, Physical effects coherent >= 4/5, Architecture unchanged >= 95%, Reflections/wetness/snow realistic >= 4/5, No excessive artificial effects.',
    prompt_version: 'change_weather:v1'
  },
  25: {
    id: 25,
    slug: 'design-to-maquette',
    name: 'Design to Maquette',
    description: 'Convert a design into a physical architectural-model aesthetic.',
    input_types: ['image/png', 'image/jpeg', 'image/webp', 'image/heic', 'image/heif'],
    output_types: ['image/png'],
    provider: 'vertex_image',
    default_model: 'gemini-3-pro-image',
    allowed_models: ['gemini-3-pro-image', 'gemini-3.1-flash-image', 'gemini-3.1-flash-lite-image'],
    model_dropdown: true,
    prompt_template: 'Convert the supplied architectural design into a professionally photographed physical architectural maquette. Preserve recognizable massing, proportions and primary geometry. Materials may include: white museum board, balsa wood, basswood, translucent acrylic, subtle grey card. Place the model on a clean architectural model base. Use professional studio tabletop photography and model-scale shadows. The result must clearly read as a physical scale model rather than a full-size real building.',
    required_fields: ['source_image'],
    optional_fields: ['maquette_material', 'style'],
    default_values: {},
    estimated_time: '10-35 sec',
    async: false,
    manual_test_criteria: 'Original massing recognizability >= 4/5, Clearly reads as physical model >= 4/5, Model material realism >= 4/5, Scale cues convincing, No major geometry change.',
    prompt_version: 'design_to_maquette:v1'
  },
  26: {
    id: 26,
    slug: 'upscale-and-enhance',
    name: 'Upscale & Enhance',
    description: 'Increase apparent detail/resolution of a render.',
    input_types: ['image/png', 'image/jpeg', 'image/webp', 'image/heic', 'image/heif'],
    output_types: ['image/png'],
    provider: 'vertex_image',
    default_model: 'gemini-3-pro-image',
    allowed_models: ['gemini-3-pro-image'],
    model_dropdown: false,
    prompt_template: 'Enhance the supplied architectural render to high-resolution professional presentation quality. Preserve exactly: composition, geometry, architecture, camera, objects, materials, colors, lighting. Improve only: micro-detail, texture clarity, edge quality, material definition, subtle reflections, fine architectural details, natural photographic sharpness. Do not hallucinate new design elements. Do not oversharpen.',
    required_fields: ['source_image'],
    optional_fields: ['upscale_factor'],
    default_values: { upscale_factor: '4x' },
    estimated_time: '15-50 sec',
    async: false,
    manual_test_criteria: 'Output resolution increased, Fine-detail improvement >= 4/5, No hallucinated architecture, No material redesign, No oversharpening, Original composition preserved.',
    prompt_version: 'upscale_and_enhance:v1'
  },
  27: {
    id: 27,
    slug: 'upscale-video',
    name: 'Upscale Video',
    description: 'Increase video resolution.',
    input_types: ['video/mp4'],
    output_types: ['video/mp4'],
    provider: 'veo_video',
    default_model: 'veo-3.1-lite',
    allowed_models: ['veo-3.1-lite'],
    model_dropdown: false,
    prompt_template: '',
    required_fields: ['source_video'],
    optional_fields: ['target_resolution'],
    default_values: { target_resolution: '1080p' },
    estimated_time: '1-10 min',
    async: true,
    manual_test_criteria: 'Resolution visibly improved, Video duration unchanged, No introduced geometry distortion, No flicker increase, Motion remains smooth, Audio preserved.',
    prompt_version: 'upscale_video:v1'
  },
  28: {
    id: 28,
    slug: 'image-to-video',
    name: 'Image to Video',
    description: 'Animate a static render into cinematic video.',
    input_types: ['image/png', 'image/jpeg', 'image/webp', 'image/heic', 'image/heif'],
    output_types: ['video/mp4'],
    provider: 'veo_video',
    default_model: 'veo-3.1-lite',
    allowed_models: ['veo-3.1-lite'],
    model_dropdown: false,
    prompt_template: 'Create professional architectural cinematography beginning from the supplied image. Maintain architecture, furniture, materials, landscape and project identity. CAMERA MOVEMENT: {{camera_motion}}\nSPEED: {{speed}}\nSHOT TYPE: {{shot_type}}\nUse smooth stabilized professional motion. Maintain consistent architectural geometry and object identity. Avoid geometry morphing, moving walls, moving furniture, camera shake and sudden zoom. Use natural parallax and smooth acceleration/deceleration.',
    required_fields: ['source_image', 'camera_motion'],
    optional_fields: ['speed', 'shot_type', 'audio', 'duration_seconds', 'resolution'],
    default_values: { duration_seconds: 4, resolution: '720p', audio: false },
    estimated_time: '1-5 min',
    async: true,
    manual_test_criteria: 'Camera movement matches request >= 4/5, Architecture stable >= 4/5, No object morphing, Motion smooth >= 4/5, Source identity maintained, Video valid.',
    prompt_version: 'image_to_video:v1'
  },
  29: {
    id: 29,
    slug: 'image-to-3d-model',
    name: 'Image to 3D Model',
    description: 'Convert an object image into a reusable textured 3D asset.',
    input_types: ['image/png', 'image/jpeg', 'image/webp', 'image/heic', 'image/heif'],
    output_types: ['model/gltf-binary'],
    provider: 'trellis_3d',
    default_model: 'TRELLIS.2-4B',
    allowed_models: ['TRELLIS.2-4B'],
    model_dropdown: false,
    prompt_template: '',
    required_fields: ['source_image'],
    optional_fields: [],
    default_values: { task: 'image_to_3d' },
    estimated_time: '2-6 min',
    async: true,
    manual_test_criteria: 'Rotate result 360 deg: Silhouette match >= 4/5, Proportions >= 4/5, Texture correspondence >= 4/5, Back/side plausible, No severe holes, GLB imports correctly.',
    prompt_version: 'image_to_3d_model:v1'
  },
  30: {
    id: 30,
    slug: 'image-to-scene',
    name: 'Image to Scene',
    description: 'Convert room imagery into an explorable scene.',
    input_types: ['image/png', 'image/jpeg', 'image/webp', 'image/heic', 'image/heif'],
    output_types: ['application/octet-stream'],
    provider: 'trellis_3d',
    default_model: 'TRELLIS.2-4B',
    allowed_models: ['TRELLIS.2-4B', 'GSplat'],
    model_dropdown: true,
    prompt_template: '',
    required_fields: ['source_image'],
    optional_fields: [],
    default_values: { task: 'generate_scene', format: 'splat' },
    estimated_time: '3-10 min',
    async: true,
    manual_test_criteria: 'Scene opens successfully, Navigation stable, Primary room proportions >= 4/5, Major furniture placement >= 4/5, No severe floating geometry, No catastrophic holes.',
    prompt_version: 'image_to_scene:v1'
  },
  31: {
    id: 31,
    slug: 'reference-guided',
    name: 'Reference Guided',
    description: 'This workflow creates architectural or interior renders using design drawings and visual references. The drawing guides the core design—layout, geometry, proportions, openings, and key spatial details—while reference images guide the style, materials, lighting, colors, and overall mood. Users can also add a text prompt for specific instructions. The final render should stay faithful to the design while adopting the desired visual character from the references.',
    input_types: ['image/png', 'image/jpeg', 'image/webp', 'image/heic', 'image/heif', 'text'],
    output_types: ['image/png'],
    provider: 'vertex_image',
    default_model: 'gemini-3-pro-image',
    allowed_models: ['gemini-3-pro-image', 'gemini-3.1-flash-image', 'gemini-3.1-flash-lite-image', 'flux-2-pro', 'stable-diffusion-xl'],
    model_dropdown: true,
    prompt_template: 'TASK: Create a photorealistic architectural visualization using dual-channel drawing and reference guidance.\nDRAWING AUTHORITY: The attached design drawing strictly dictates the spatial layout, architectural geometry, wall partitions, openings, window placement, and core structural proportions.\nREFERENCE GUIDANCE: Extract and synthesize material textures, lighting conditions, atmosphere, color palette, and visual style from the attached reference images.\nDESIGN STYLE: {{style}}\nMATERIALS: {{materials}}\nLIGHTING: {{lighting}}\nENVIRONMENT: {{environment}}\nUSER INSTRUCTIONS: {{custom_instruction}}\n{{UNIVERSAL_QUALITY_BLOCK}}',
    required_fields: ['drawing_image'],
    optional_fields: ['reference_images', 'user_input', 'style', 'materials', 'lighting', 'environment', 'mood', 'custom_instruction'],
    default_values: { controlnet_conditioning_scale: 0.85 },
    estimated_time: '10-35 sec (Pro) / 4-12 sec (Flash)',
    async: false,
    manual_test_criteria: 'Core design drawing layout and openings preserved >= 95%, Reference style/material fidelity transferred >= 4/5, Photorealism >= 4/5, Cohesive architectural lighting and perspective synthesis.',
    prompt_version: 'reference_guided:v1'
  }
};

const HUB_MAPPING: Record<number, 'image_studio' | 'raster_canvas' | 'video_studio' | 'gen_3d'> = {
  1: 'image_studio',
  2: 'image_studio',
  3: 'image_studio',
  4: 'image_studio',
  5: 'image_studio',
  6: 'image_studio',
  7: 'raster_canvas',
  8: 'image_studio',
  9: 'raster_canvas',
  10: 'image_studio',
  11: 'raster_canvas',
  12: 'raster_canvas',
  13: 'raster_canvas',
  14: 'raster_canvas',
  15: 'raster_canvas',
  16: 'raster_canvas',
  17: 'raster_canvas',
  18: 'raster_canvas',
  19: 'video_studio',
  20: 'image_studio',
  21: 'raster_canvas',
  22: 'image_studio',
  23: 'image_studio',
  24: 'image_studio',
  25: 'image_studio',
  26: 'image_studio',
  27: 'video_studio',
  28: 'video_studio',
  29: 'gen_3d',
  30: 'gen_3d',
  31: 'image_studio',
};

export const WORKFLOWS: Record<number, Workflow> = Object.fromEntries(
  Object.entries(RAW_WORKFLOWS).map(([idStr, wf]) => {
    const id = Number(idStr);
    return [id, { ...wf, hubCategory: HUB_MAPPING[id] || 'image_studio' }];
  })
);
